### ISSUE TITLE
"add a write-in" candidate button should behave like candidate button.

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#1034] opened 2020-01-06 06:31 UTC
It's confusing when it disappears completely, there's no signal on the page that write-ins are possible.

**Comment by eventualbuddha** [comment] 2020-01-06 16:56
Seems reasonable to me. @beausmith?

**Comment by beausmith** [comment] 2020-01-07 20:39
This is a duplicate of votingworks/bmd#369 (https://github.com/votingworks/bmd/issues/369)

**Closed** 2020-02-09 05:32 UTC
Labels: [zube]: Inbox
