### ISSUE TITLE
Settings: font sizes

### ISSUE THREAD

**Issue by benadida** [votingworks/bmd#121] opened 2019-03-12 18:16 UTC

**Comment by beausmith** [comment] 2019-03-21 21:19
## Initial Questions

- What are the different font-sizes?
- What is the default size?
- How does UI adapt to font-size? Styles are all based on `rem` units which will increase/decrease sizes of padding/margin/etc.

## VVSG Requirements
https://www.eac.gov/assets/1/28/VVSG.1.1.VOL.1.FINAL1.pdf
```
3.2.5 Visual display characteristics

d. For all text intended for voters or poll workers, the voting system shall provide a
font with the following characteristics
  i. Height of capital letters at least: 3.0 mm
  ii. x-height of at least: 70% of cap height
  iii. Stroke width at least: 0.35 mm.
e. A voting system that uses an electronic image display shall be capable of showing
all information in at least two font sizes:
  i. 3.0-4.0 mm cap height, with a corresponding x-height at least 70% of the cap
height and a minimum stroke width of 0.35 mm;
  ii. 6.3-9.0 mm cap height, with a corresponding x-height at least 70% of the cap
height and a minimum stroke width of 0.7 mm; under control of the voter. The system shall allow the voter to adjust font size throughout the voting session
while preserving the current votes.
f. Text intended for the voter should be presented in a sans serif font.
```

**Comment by beausmith** [comment] 2019-06-02 04:22
Resolving as dupe of https://github.com/votingworks/bmd/issues/184

**Closed by beausmith** 2019-06-02 04:22 UTC
